// <auto-generated />
namespace SRAD_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Updatedatabase06072022 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updatedatabase06072022));
        
        string IMigrationMetadata.Id
        {
            get { return "202207061518168_Update database 06072022"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
