// <auto-generated />
namespace SRAD_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initentitydatamodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initentitydatamodels));
        
        string IMigrationMetadata.Id
        {
            get { return "202206150730494_init entity data models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
