// <auto-generated />
namespace SRAD_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateusermodelusertype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateusermodelusertype));
        
        string IMigrationMetadata.Id
        {
            get { return "202206160638429_update user model+user type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
