// <auto-generated />
namespace SRAD_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addgrademodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addgrademodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202206150749234_add grade model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
